/*
 * Copyright (c) 2024-2025 7orivorian.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package dev.tori.runtimeprofiler.write;

import dev.tori.runtimeprofiler.IProfiler;
import dev.tori.runtimeprofiler.ProfileEntry;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.io.PrintStream;
import java.text.DecimalFormat;
import java.util.Locale;

/**
 * The OutputWriter enum provides different implementations for printing profiling data to the console.
 * Each enum instance provides a specific implementation for formatting and outputting
 * the data collected by a profiler instance.
 *
 * @author <a href="https://github.com/7orivorian">7orivorian</a>
 * @since 1.2.0
 */
public enum ConsoleWriter {
    FULL {
        @Override
        public void print(@NotNull IProfiler profiler, @NotNull PrintStream out, int maxPathDepth) {
            out.println(profiler.getLabel());
            profiler.getEntries().forEach(entry -> {
                ProfileEntry data = entry.getValue();
                if (data.depth() > maxPathDepth) {
                    return;
                }
                String percent = new DecimalFormat("#.###").format(((double) data.total() / profiler.getTotalRuntime()) * 100);
                out.println(data.id() + ": visits=%s, Avg=%s, Min=%s, Max=%s, Runtime=%s, %s%s of Runtime"
                        .formatted(
                                data.visits(),
                                data.avg(),
                                data.minTime(),
                                data.maxTime(),
                                data.total(),
                                percent,
                                "%"
                        )
                );
            });
        }
    },
    AVG_ONLY {
        @Override
        public void print(@NotNull IProfiler profiler, @NotNull PrintStream out, int maxPathDepth) {
            out.println(profiler.getLabel());
            profiler.getEntries().forEach(entry -> {
                ProfileEntry data = entry.getValue();
                if (data.depth() > maxPathDepth) {
                    return;
                }
                out.println(data.id() + ": visits=%s, Avg=%s, Min=%s, Max=%s"
                        .formatted(
                                data.visits(),
                                data.avg(),
                                data.minTime(),
                                data.maxTime()
                        )
                );
            });
        }
    };

    @Contract(pure = true)
    ConsoleWriter() {

    }

    /**
     * Parses the given string to return the corresponding {@code ConsoleWriter} instance.
     *
     * @param name the name of the {@code ConsoleWriter}; must not be {@code null}.
     * @return the {@code ConsoleWriter} instance matching the given name.
     * @throws IllegalArgumentException if the given name is {@code null} or does not match any valid {@code ConsoleWriter}.
     */
    @NotNull
    public static ConsoleWriter fromString(String name) {
        if (name == null) {
            throw new IllegalArgumentException("ConsoleWriter name cannot be null");
        }
        return switch (name.toLowerCase(Locale.ROOT)) {
            case "full" -> FULL;
            case "avg" -> AVG_ONLY;
            default -> throw new IllegalArgumentException("Invalid ConsoleWriter name: " + name);
        };
    }

    /**
     * Prints data generated by the provided profiler with the given output stream.
     *
     * @param profiler the profiler instance containing the profiling data to be printed; must not be {@code null}.
     * @param out      the {@code PrintStream} to which the profiling information will be written; must not be {@code null}.
     * @see #print(IProfiler, PrintStream, int)
     */
    public void print(@NotNull IProfiler profiler, @NotNull PrintStream out) {
        print(profiler, out, Integer.MAX_VALUE);
    }

    /**
     * Prints data generated by the provided profiler with the given output stream.
     *
     * @param profiler     the profiler instance containing the profiling data to be printed; must not be {@code null}.
     * @param out          the {@code PrintStream} to which the profiling information will be written; must not be {@code null}.
     * @param maxPathDepth the maximum depth of paths to print; provides control on the level of detail in the output.
     */
    public abstract void print(@NotNull IProfiler profiler, @NotNull PrintStream out, int maxPathDepth);
}